### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by keloemma** [kabirahuja2431/FineTuneBERT#4]
I am testing your proposed answer to finetune BERT and I am encountering this pb , could you help me figure out the pb?

(env) kel@hyp:~/eXP/FineTuneBERT$ python -m src.main -gpu 1 -maxlen 32 -batch_size 8 -lr 0.00005 -max_eps 4 -freeze_bert
Building model! (This might take time if you are running this for first time)
Done in 4.084611415863037 seconds
Creating criterion and optimizer objects
Done in 0.0009949207305908203 seconds
Creating train and val dataloaders
Done in 1.1422762870788574 seconds
Let the training begin
Traceback (most recent call last):
  File "/home/get/ke/anaconda3/envs/env/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/get/ke/anaconda3/envs/env/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/get/ke/eXP/FineTuneBERT/src/main.py", line 109, in <module>
    train(net, criterion, opti, train_loader, val_loader, args)
  File "/home/ge/k/eXP/FineTuneBERT/src/main.py", line 50, in train
    logits = net(seq, attn_masks)
  File "/home/ge/ke/anaconda3/envs/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/get/ke/eXP/FineTuneBERT/src/model.py", line 28, in forward
    cont_reps, _ = self.bert_layer(seq, attention_mask = attn_masks)
  File "/home/get/ke/anaconda3/envs/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/getalp/kelodjoe/transformers/src/transformers/modeling_bert.py", line 755, in forward
    extended_attention_mask = extended_attention_mask.to(dtype=next(self.parameters()).dtype)  # fp16 compatibility
RuntimeError: CUDA error: no kernel image is available for execution on the device

#####################

~$ cat /usr/local/cuda/version.txt
CUDA Version 7.5.18
(env) kel@hy:~$ python -c "import torch; print(torch.__version__)"
1.3.1
:~$ python -c "import pandas; print(pandas.__version__)"
0.25.3
:~$ python -c "import numpy; print(numpy.__version__)"
1.17.4
:~$ python -c "import transformers; print(transformers.__version__)"
2.3.0

Is it related to the version I have on computer ?

**Comment by keloemma** [comment]
I found the proble I have to change the servers I find one which was suitable and it worked than you!!!
