### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'Models/sstcls_0_freeze_True.dat'

### ISSUE THREAD

**Issue by keloemma** [kabirahuja2431/FineTuneBERT#5]
Good morning:

The script is working well but I get this error ?

Iteration 8000 of epoch 0 complete. Loss : 0.4000898599624634 Accuracy : 0.875
Iteration 8100 of epoch 0 complete. Loss : 0.648669958114624 Accuracy : 0.625
Iteration 8200 of epoch 0 complete. Loss : 0.6150379180908203 Accuracy : 0.5
Iteration 8300 of epoch 0 complete. Loss : 0.3642449975013733 Accuracy : 0.875
Iteration 8400 of epoch 0 complete. Loss : 0.24585166573524475 Accuracy : 1.0
Epoch 0 complete! Validation Accuracy : 0.831421971321106, Validation Loss : 0.420876018497922
Best validation accuracy improved from 0 to 0.831421971321106, saving model...
Traceback (most recent call last):
  File "/home/getalp/kelodjoe/anaconda3/envs/env/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/getalp/kelodjoe/anaconda3/envs/env/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data1/home/getalp/kelodjoe/eXP/FineTuneBERT/src/main.py", line 109, in <module>
    train(net, criterion, opti, train_loader, val_loader, args)
  File "/data1/home/getalp/kelodjoe/eXP/FineTuneBERT/src/main.py", line 71, in train
    torch.save(net.state_dict(), 'Models/sstcls_{}_freeze_{}.dat'.format(ep, args.freeze_bert))
  File "/home/getalp/kelodjoe/anaconda3/envs/env/lib/python3.6/site-packages/torch/serialization.py", line 260, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/getalp/kelodjoe/anaconda3/envs/env/lib/python3.6/site-packages/torch/serialization.py", line 183, in _with_file_like
    f = open(f, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'Models/sstcls_0_freeze_True.dat'

**Comment by kabirahuja2431** [comment]
Create a Models directory in the directory from where you are running the code.

cd FineTuneBERT
mkdir Models

This should work.
